# Generated by Django 4.1.7 on 2023-05-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('add', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('percentage', models.FloatField()),
                ('package', models.IntegerField()),
            ],
        ),
    ]
