# Generated by Django 4.1.7 on 2023-05-20 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='subject',
        ),
    ]
